name: wiselover
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_wiselover:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  sherpa_onnx: ^1.12.20
  http: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.8.1
  file_picker: ^8.1.4
  archive: ^4.0.7
  shared_preferences: ^2.3.3

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/live2d/mao_pro/
    - assets/live2d/mao_pro/runtime/mao_pro.moc3
    - assets/live2d/mao_pro/runtime/mao_pro.model3.json
    - assets/live2d/mao_pro/runtime/mao_pro.physics3.json
    - assets/live2d/mao_pro/runtime/mao_pro.pose3.json
    - assets/live2d/mao_pro/runtime/mao_pro.cdi3.json
    - assets/live2d/mao_pro/runtime/mao_pro.4096/texture_00.png
    - assets/live2d/mao_pro/runtime/motions/
    - assets/live2d/mao_pro/runtime/expressions/
    - assets/live2d/juanjuan/
    - assets/live2d/juanjuan/juanjuan.moc3
    - assets/live2d/juanjuan/juanjuan.model3.json
    - assets/live2d/juanjuan/juanjuan.physics3.json
    - assets/live2d/juanjuan/juanjuan.cdi3.json
    - assets/live2d/juanjuan/juanjuan.8192/texture_00.png
    - assets/live2d/juanjuan/juanjuan.8192/texture_01.png
    - assets/live2d/PurpleBird/PurpleBird.moc3
    - assets/live2d/PurpleBird/PurpleBird.model3.json
    - assets/live2d/PurpleBird/PurpleBird.physics3.json
    - assets/live2d/PurpleBird/PurpleBird.cdi3.json
    - assets/live2d/PurpleBird/PurpleBird.4096/texture_00.png
    - assets/live2d/PurpleBird/PurpleBird.4096/texture_01.png
    - assets/live2d/PurpleBird/PurpleBird.4096/texture_02.png
    - assets/live2d/PurpleBird/PurpleBird.4096/texture_03.png
    - assets/live2d/PurpleBird/PurpleBird.4096/texture_04.png
    
    - assets/sherpa/chinese/encoder.int8.onnx
    - assets/sherpa/chinese/decoder.onnx
    - assets/sherpa/chinese/joiner.int8.onnx
    - assets/sherpa/chinese/tokens.txt
    - assets/sherpa/chinese/bpe.model


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
